### ISSUE TITLE
1.18.2 Error PathGoal

### ISSUE THREAD

**Issue by ArubikU** [GamerCoder215/MobChip#12] opened 2022-09-17 21:32 UTC
### Bug Type

Console Errors

### Description

org.bukkit.command.CommandException: Unhandled exception executing command 'mctl' in plugin Minecraft_Comes_to_Life v1.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2390) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2182) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$13664/0x0000000008174168.run(Unknown Source) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer$$Lambda$4174/0x0000000036815640.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:884) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:184) ~[?:?]
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173) ~[?:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2$5.<clinit>(ChipUtil1_18_R2.java:986) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2.toNMS(ChipUtil1_18_R2.java:1658) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2$$Lambda$14363/0x00000000f7a6a710.apply(Unknown Source) ~[mctl-1.0.0.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2.custom(ChipUtil1_18_R2.java:1779) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2.toNMS(ChipUtil1_18_R2.java:377) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2.addPathfinder(ChipUtil1_18_R2.java:391) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil.addPathfinders(ChipUtil.java:53) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.bukkit.BukkitAI.updateAI(BukkitAI.java:43) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.bukkit.BukkitAI.add(BukkitAI.java:113) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.bukkit.BukkitAI.put(BukkitAI.java:70) ~[mctl-1.0.0.jar:?]
        at us.ayo.mctl.holders.EntityAi.follow(EntityAi.java:46) ~[mctl-1.0.0.jar:?]
        at us.ayo.mctl.enums.mood.speech(mood.java:105) ~[mctl-1.0.0.jar:?]
        at us.ayo.mctl.holders.CommandHolder.onCommand(CommandHolder.java:583) ~[mctl-1.0.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
Caused by: java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: 
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:52) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.NamespacedKey.minecraft(NamespacedKey.java:145) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at me.gamercoder215.mobchip.ai.animation.EntityAnimation.<init>(EntityAnimation.java:38) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.ai.animation.EntityAnimation.<clinit>(EntityAnimation.java:16) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2$5.<clinit>(ChipUtil1_18_R2.java:986) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2.toNMS(ChipUtil1_18_R2.java:1658) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2$$Lambda$14363/0x00000000f7a6a710.apply(Unknown Source) ~[mctl-1.0.0.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2.custom(ChipUtil1_18_R2.java:1779) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2.toNMS(ChipUtil1_18_R2.java:377) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2.addPathfinder(ChipUtil1_18_R2.java:391) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil.addPathfinders(ChipUtil.java:53) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.bukkit.BukkitAI.updateAI(BukkitAI.java:43) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.bukkit.BukkitAI.add(BukkitAI.java:113) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.bukkit.BukkitAI.put(BukkitAI.java:70) ~[mctl-1.0.0.jar:?]
        at us.ayo.mctl.holders.EntityAi.follow(EntityAi.java:46) ~[mctl-1.0.0.jar:?]
        at us.ayo.mctl.enums.mood.speech(mood.java:105) ~[mctl-1.0.0.jar:?]
        at us.ayo.mctl.holders.CommandHolder.onCommand(CommandHolder.java:583) ~[mctl-1.0.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more

Pom:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>us.ayo.mctl</groupId>
    <artifactId>mctl</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>Minecraft Comes to Life</name>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
        <repository>
            <id>papermc</id>
            <url>https://papermc.io/repo/repository/maven-public/</url>
        </repository>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>

        <repository>
            <id>codemc-releases</id>
            <url>https://repo.codemc.org/repository/maven-releases/</url>
        </repository>

        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>phoenix</id>
            <url>https://nexus.phoenixdvpt.fr/repository/maven-public/</url>
        </repository>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>lumine-repo</id>
            <url>https://mvn.lumine.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>md5</id>
            <url>http://repo.md-5.net/content/groups/public</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>dmulloy2-repo</id>
            <url>https://repo.dmulloy2.net/repository/public/</url>
        </repository>
    </repositories>

    <dependencies>
        
        
        <dependency>
            <groupId>com.github.GamerCoder215.MobChip</groupId>
            <artifactId>mobchip-bukkit</artifactId>
            <version>1.5.0</version> 
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.github.GamerCoder215.MobChip</groupId>
            <artifactId>mobchip-base</artifactId>
            <version>1.5.1</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
         <groupId>me.clip</groupId>
          <artifactId>placeholderapi</artifactId>
          <version>2.11.2</version>
         <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.libd</groupId>
            <artifactId>sample</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/LibsDisguises-10.0.27-Free.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.libm</groupId>
            <artifactId>sample</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/mythicmobs.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.libs</groupId>
            <artifactId>sample</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/Shopkeepers-2.16.2.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>com.libc</groupId>
            <artifactId>sample</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/citizens.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>net.skinsrestorer</groupId>
            <artifactId>skinsrestorer-api</artifactId>
            <version>14.2.3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.comphenix.protocol</groupId>
            <artifactId>ProtocolLib</artifactId>
            <version>4.8.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.19.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>io.lumine</groupId>
            <artifactId>MythicLib-dist</artifactId> 
            <version>1.4.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>

### Expected Behavior

Work ps :/

### Actual Behavior

The ai is throwing a error no NameSpace

**Comment by datatags** [comment] 2022-09-17 22:19
Duplicate of #8, which was fixed in `1.5.1-SNAPSHOT` so please try that version

**Comment by ArubikU** [comment] 2022-09-17 22:39
> Duplicate of #8, which was fixed in `1.5.1-SNAPSHOT` so please try that version

I try to put this version but jitpack dont read

**Comment by ArubikU** [comment] 2022-09-17 22:50
![image](https://user-images.githubusercontent.com/102335860/190878814-94a4561c-06b3-47d6-9332-bfceb8e2aa62.png)

**Comment by ArubikU** [comment] 2022-09-17 23:00
![image](https://user-images.githubusercontent.com/102335860/190878999-bac0a422-66e2-4c05-9302-05d3b5435539.png)

**Comment by GamerCoder215** [comment] 2022-09-17 23:02
It's building with JDK 8:

I would recommend switching your dependency to CodrMC's format.

**Closed** 2022-09-17 23:04 UTC
Labels: duplicate

**Comment by ArubikU** [comment] 2022-09-17 23:10
> me.gamercoder215

![image](https://user-images.githubusercontent.com/102335860/190879194-22e06dc3-f5e2-48ca-a702-ef38a95cc164.png)

**Comment by GamerCoder215** [comment] 2022-09-18 00:56
> > me.gamercoder215
> 
> ![image](https://user-images.githubusercontent.com/102335860/190879194-22e06dc3-f5e2-48ca-a702-ef38a95cc164.png)

Make sure you add the `codemc-snapshots` repository.

**Comment by ArubikU** [comment] 2022-09-19 01:50
What is this??
I didnt see this in the read.me

**Comment by ArubikU** [comment] 2022-09-19 02:52
> > > me.gamercoder215
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/102335860/190879194-22e06dc3-f5e2-48ca-a702-ef38a95cc164.png)
> 
> Make sure you add the `codemc-snapshots` repository.

Caused by: java.lang.NoSuchMethodError: net/minecraft/world/entity/ai/goal/PathfinderGoal.j()Ljava/util/EnumSet; (loaded from file:/home/container/versions/1.18.2/purpur-1.18.2.jar by java.net.URLClassLoader@b2a1bc9b) called from class me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2$4 (loaded from file:/home/container/./plugins/mctl-1.0.0.jar by PluginClassLoader{plugin=Minecraft_Comes_to_Life v1.0.0, pluginEnabled=true, url=./plugins/mctl-1.0.0.jar}).
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2$4.getFlags(ChipUtil1_18_R2.java:1787) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2.custom(ChipUtil1_18_R2.java:1779) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2.toNMS(ChipUtil1_18_R2.java:377) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil1_18_R2.addPathfinder(ChipUtil1_18_R2.java:391) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.abstraction.ChipUtil.addPathfinders(ChipUtil.java:53) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.bukkit.BukkitAI.updateAI(BukkitAI.java:43) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.bukkit.BukkitAI.add(BukkitAI.java:113) ~[mctl-1.0.0.jar:?]
        at me.gamercoder215.mobchip.bukkit.BukkitAI.put(BukkitAI.java:70) ~[mctl-1.0.0.jar:?]
        at us.ayo.mctl.holders.EntityAi.follow(EntityAi.java:46) ~[mctl-1.0.0.jar:?]
        at us.ayo.mctl.enums.mood.speech(mood.java:121) ~[mctl-1.0.0.jar:?]
        at us.ayo.mctl.holders.CommandHolder.onCommand(CommandHolder.java:583) ~[mctl-1.0.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more

well now I have that error
